apps/users/urls.py
from django.urls import path
from django.urls import path, re_path, include
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import reverse_lazy
from . import views
from django.conf.urls import url
from .ajax import *

urlpatterns = [
	path('login/', views.login, name='login'),
	path('logout/', views.logout, name='logout'),
	    #Reestablecimiento de password
	path('reset/password_reset', PasswordResetView.as_view(template_name='users/password_reset_form.html', email_template_name="users/password_reset_email.html"), name = 'password_reset'),
    path('reset/password_reset_done', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name = 'password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-za-z_\-]+)/(?P<token>.+)/$', PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name = 'password_reset_confirm'),
    path('reset/done',PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html') , name = 'password_reset_complete'),
	path('gestion_laboratoristas/', views.gestion_laboratorista, name='gestion_laboratorista'),
	path('gestion_minsal/', views.gestion_minsal, name='gestion_minsal'),
	path('eliminar-laboratorista/', views.eliminar_laboratorista, name='eliminar_laboratorista'),
	path('registrar-laboratorista/', views.registrar_laboratorista, name='registrar_laboratorista'),
	path('editar-laboratorista/', views.editar_laboratorista, name='editar_laboratorista'),
	path('eliminar-minsal', views.eliminar_minsal, name='eliminar_minsal'),
	path('registrar-minsal/', views.registrar_minsal, name='registrar_minsal'),
	path('editar-minsal/', views.editar_minsal, name='editar_minsal'),
	path('gestion_paciente/', views.gestion_paciente, name='gestion_paciente'),
	url(r'ajax/get_municipios', get_municipios, name='get_municipios'),
	path('registrar-paciente/', views.registrar_paciente, name='registrar_paciente'),
	path('editar-paciente/', views.editar_paciente, name='editar_paciente'),
	path('caso-sospechoso', views.caso_sospechoso, name='caso_sospechoso'),
	path('nexos/<int:cuadro_id>', views.nexo, name='nexo'),	
	path('registrar-nexo/', views.registrar_nexo, name='registrar_nexo'),
]

covidsv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.covid.urls')),
    path('usuarios/', include('apps.users.urls')),
]

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.

class User(AbstractUser):
    pass
    rol = models.IntegerField(default=0)
    dui = models.CharField(max_length=9, null=False, blank = False)
    direccion = models.CharField(max_length=250, null=True)

apps/users/forms.py
# users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import User
from apps.covid.models import Municipio, Departamento


class UserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'rol', 'direccion')

class UserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('username', 'email', 'rol', 'direccion')

class FormFiltrar(forms.Form):

    departamento = forms.ModelChoiceField(
        label=u'', 
        queryset=Departamento.objects.all(),
        widget=forms.Select(attrs={'class':'form-control'}),
    )
    
    municipio = forms.ModelChoiceField(
        label=u'', 
        queryset=Municipio.objects.all(),
        widget=forms.Select(attrs={'class':'form-control'}),
    )

apps/users/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.models import auth
from django.contrib import messages
from .models import User
from django.core import mail
from apps.covid.models import *
from .forms import FormFiltrar
from datetime import date, datetime

departamentos = Departamento.objects.all()
municipios = Municipio.objects.all()

def login(request):

	if(request.method == 'POST'):

		username = request.POST['username']
		password = request.POST['password']

		user = auth.authenticate(username=username,password=password)

		if user is not None:
			auth.login(request, user)
			return redirect('/')
		else:
			messages.error(request,'Credenciales inválidas')
			return redirect('/')

	else:
		return render(request,'users/login.html')
def logout(request):
	auth.logout(request)
	return redirect('/')

def gestion_laboratorista(request):	
	if(request.user.is_authenticated and request.user.rol == 0):
		laboratoristas = Laboratorista.objects.all()
		contexto = {'laboratoristas': laboratoristas,}
		return render(request, 'gestion_usuarios/gestion_laboratorista.html', contexto)
	else:
		contexto = {}
		return redirect('/')

def eliminar_laboratorista(request):

	Laboratorista.objects.filter(id=request.POST['id_delete']).delete()
	User.objects.filter(pk=request.POST['user_delete']).delete()

	return redirect('gestion_laboratorista')

def registrar_laboratorista(request):

	nombre = request.POST['nombre']
	apellido = request.POST['apellido']
	usuario = request.POST['usuario']
	correo = request.POST['correo']
	password = request.POST['password']
	password_2 = request.POST['password-2']
	dui = request.POST['telefono']
	direccion = request.POST['direccion']
	activo = True
	staff = True
	rol = 1

	user, laboratorista = User.objects.get_or_create(
		username = usuario,
		first_name = nombre,
		last_name = apellido,
		email = correo,
		password = password,
		dui = dui,
		direccion = direccion,
		rol = rol,
		is_active = activo,
		is_staff = staff
	)
	
	if laboratorista:
		user.set_password(password)
		user.save()

	covid_laboratorista = Laboratorista()

	covid_laboratorista.user = user

	covid_laboratorista.save()

	if request.user.is_authenticated:

		return redirect('gestion_laboratorista')

	else:
		
		return redirect('/')

def editar_laboratorista(request):

	laboratorista = Laboratorista.objects.get(pk=request.POST['id_edit'])

	laboratorista.user.first_name = request.POST['nombre_edit']
	laboratorista.user.last_name = request.POST['apellido_edit']
	laboratorista.user.username = request.POST['usuario_edit']
	laboratorista.user.email = request.POST['correo_edit']
	laboratorista.user.dui = request.POST['telefono_edit']
	laboratorista.user.direccion = request.POST['direccion_edit']
	laboratorista.user.save()
	laboratorista.save()

	return redirect('gestion_laboratorista')

def gestion_minsal(request):
	if(request.user.is_authenticated and request.user.rol == 0):
		minsal = Minsal.objects.all()
		contexto = {'minsal': minsal,}
		return render(request, 'gestion_usuarios/gestion_minsal.html', contexto)
	else:
		contexto = {}
		return redirect('/')


def eliminar_minsal(request):

	Minsal.objects.filter(id=request.POST['id_delete']).delete()
	User.objects.filter(pk=request.POST['user_delete']).delete()

	return redirect('gestion_minsal')

def registrar_minsal(request):

	nombre = request.POST['nombre']
	apellido = request.POST['apellido']
	usuario = request.POST['usuario']
	correo = request.POST['correo']
	password = request.POST['password']
	password_2 = request.POST['password-2']
	dui = request.POST['telefono']
	direccion = request.POST['direccion']
	activo = True
	staff = True
	rol = 2

	user, minsal = User.objects.get_or_create(
		username = usuario,
		first_name = nombre,
		last_name = apellido,
		email = correo,
		password = password,
		dui = dui,
		direccion = direccion,
		rol = rol,
		is_active = activo,
		is_staff = staff
	)
	
	if minsal:
		user.set_password(password)
		user.save()

	covid_minsal = Minsal()

	covid_minsal.user = user

	covid_minsal.save()

	if request.user.is_authenticated:

		return redirect('gestion_minsal')

	else:
		
		return redirect('/')

def editar_minsal(request):

	minsal = Minsal.objects.get(pk=request.POST['id_edit'])

	minsal.user.first_name = request.POST['nombre_edit']
	minsal.user.last_name = request.POST['apellido_edit']
	minsal.user.username = request.POST['usuario_edit']
	minsal.user.email = request.POST['correo_edit']
	minsal.user.dui = request.POST['telefono_edit']
	minsal.user.direccion = request.POST['direccion_edit']
	minsal.user.save()
	minsal.save()

	return redirect('gestion_minsal')


def gestion_paciente(request):
	if(request.user.is_authenticated and (request.user.rol == 0 or request.user.rol == 1)):
		pacientes = CuadroMedico.objects.all().select_related()
		form = FormFiltrar()
		contexto = {'pacientes': pacientes,'form':form,}
		return render(request, 'gestion_usuarios/gestion_paciente.html', contexto)

	else:
		return redirect('/')	

def registrar_paciente(request):
	nombre_paciente = request.POST['nombre']
	apellido_paciente = request.POST['apellido']
	dui = request.POST['dui']
	sexo = request.POST['sexo']
	d = datetime.strptime(request.POST['fecha'], '%Y-%m-%d')
	d.strftime('%Y-%m-%d')

	localidad = Municipio.objects.get(idMunicipio=request.POST['municipio'])

	paciente = Paciente()
	paciente.localidad = localidad
	paciente.nombre_paciente = nombre_paciente
	paciente.apellido_paciente = apellido_paciente
	paciente.dui_paciente = dui
	paciente.sexo_paciente = sexo
	paciente.fecha_paciente = d
	paciente.save()

	cuadro = CuadroMedico()
	cuadro.paciente = paciente
	cuadro.estado_paciente = request.POST['estado']
	cuadro.save()

	if request.user.is_authenticated:

		return redirect('gestion_paciente')

	else:
		
		return redirect('/')


def editar_paciente(request):
	
	paciente = Paciente.objects.get(pk=request.POST['id_edit'])

	paciente.nombre_paciente = request.POST['nombre_edit']
	paciente.apellido_paciente = request.POST['apellido_edit']
	paciente.dui_paciente = request.POST['dui_edit']
	cuadroMedico = CuadroMedico.objects.get(paciente=paciente)
	cuadroMedico.estado_paciente = request.POST['estado_edit']
	paciente.sexo_paciente = request.POST['sexo_edit']
	paciente.fecha_paciente = request.POST['fecha_edit']
	#localidad = Municipio.objects.get(idMunicipio=request.POST['municipio'])
	#paciente.localidad = localidad

	if request.user.rol == 0:
		cuadroMedico.descripcion_paciente = request.POST['sintomas']
	cuadroMedico.save()
	paciente.save()
	return redirect('gestion_paciente')

def caso_sospechoso(request):	
	if(request.user.is_authenticated and request.user.rol == 0):
		cuadros = CuadroMedico.objects.all()
		contexto = {'cuadros': cuadros}
		return render(request, 'expediente/casos-sospechosos.html', contexto)
	else:
		return redirect('/')	

def nexo(request,cuadro_id):
	if(request.user.is_authenticated and request.user.rol == 0):
		cuadros = CuadroMedico.objects.get(pk=cuadro_id)
		casos = CasoSospechoso.objects.filter(cuadro=cuadros)

		contexto = {
			'cuadros':cuadros,
			'casos':casos,
		}

		return render(request, 'expediente/nexos/nexos.html', contexto)
	else:
		return redirect('/')	

def registrar_nexo(request):
	cuadros = CuadroMedico.objects.get(pk=request.POST['cuadro_id'])
	nombre_sospechoso = request.POST['nombre']
	apellido_sospechoso = request.POST['apellido']
	sexo = request.POST['sexo']
	d = datetime.strptime(request.POST['fecha'], '%Y-%m-%d')
	d.strftime('%Y-%m-%d')

	sospechoso = CasoSospechoso()
	sospechoso.nombre_sospechoso = nombre_sospechoso
	sospechoso.apellido_sospechoso = apellido_sospechoso
	sospechoso.sexo_sospechoso = sexo
	sospechoso.fecha_sospechoso = d
	sospechoso.cuadro = cuadros
	sospechoso.save()

	if request.user.is_authenticated:

		return redirect('nexo', cuadro_id=request.POST['cuadro_id'])

	else:
		
		return redirect('/')

apps/users/templates/gestion_usuarios/editar_paciente.html
{% extends 'base/base.html' %}

{% block main_container %}
{{paciente.nombre_paciente}}
{% endblock %}

apps/users/templates/gestion_usuarios/gestion_paciente.html
{% extends 'base/base.html' %}
{% load static %}
{% block main_container %}
{% if request.user.rol == 0 %}
		<!-- Vista para Doctor -->
		{% include 'gestion_usuarios/gestion_paciente_doctor.html' %}
	{% elif request.user.rol == 1 %}
		<!-- Vista para Laboratorista -->
		{% include 'gestion_usuarios/gestion_paciente_laboratorista.html' %}
	{% else %}
		<center>
			<h1>Nada que ver...</h1>
		</center>
	{% endif %}

{% endblock %}

{% block extra_js %}
<script src="{% static '/js/paciente.js' %}"></script>
{% endblock %}

apps/users/templates/gestion_usuarios/gestion_paciente_doctor.html
<script>
       $(document).ready(function() {
            $("#Editar").click(function(){
				var id = $("#id-edit").val();
            	var nombre = $("#nombre").val();
                var apellido = $("#apellido").val();
                var dui = $("#dui").val();
                var resultado = $("#estado").val();
                var sexo = $("sexo").val();
                var fecha = $("fecha").val();
                var municipio = $("id_municipio").val();
                var letra, numero;

                 letra=/^[a-zA-ZáÁéÉíÍóÓúÚñÑüÜ\s]+$/;
                 correo = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
                 numero = /^([0-9])*$/;

                if(id === "" || nombre === "" || apellido === "" || usuario === "" || email === "" || telefono === "" || direccion === ""  ){

                	alert("Todos los campos son obligatorios");

                	return false;
              	    }
                	if(!letra.test(nombre)){
                		alert("El nombre es incorrecto");
                		return false;
                		
                	}else if(nombre.length > 30){
                		alert("El nombre es demasiado largo");
                		return false;
                	}
             		
             		if(!letra.test(apellido)){
             			alert("El apellido es incorrecto");
             			return false;
             		}else if(apellido.length > 30){
                		alert("El apellido es demasiado largo");
                		return false;
                	}
                	if(usuario.length > 15){
                		alert("El nombre de usuario es demasiado largo");
                		return false;
                	}
                	
                	if(!correo.test(email)){
                		alert("El correo ingresado es incorrecto");
                		return false;
                	}
                	
					if(!numero.test(telefono) || telefono.length > 9 || telefono.length < 9){
						alert("El numero de telefono es incorrecto");
						return false;
					}
					if(direccion.length > 50){
						alert("La direccion es demasiado larga");
						return false;

					}

				});
        	});
</script>
<script type="text/javascript">

            $(document).ready(function() {
                $("#id_departamento").on("change", getMunicipios);
                $("#filtrarInfo").on("click", getInfo);
            });

            function getMunicipios() {
                var departamentoId = $("#id_departamento").val();
                if (departamentoId) {
                    // Eliminamos las opciones anteriores del select
                    $("#id_municipio").html("");
                    var request = $.ajax({
                        type: "GET",
                        url: "{% url 'get_municipios' %}",
                        data: {
                            "departamento_id": departamentoId,
                        },
                    });
                    request.done(function(response) {
                        // Agregamos los resultados al select
                        $("#id_municipio").html(response.municipios);
                        $("#id_municipio").trigger("change");
                    });
                } else {
                    $("#id_municipio").html("<option value='' selected='selected'>--------</option>");
                    $("#id_municipio").trigger("change");
                }
            }
</script>
<div class="col-md-11 py-3 px-4 main-container">
	{% csrf_token %}
	<h4>Administraci&oacute;n de Pruebas por Paciente</h4>

	<p class="lead">Estos son los pacientes registrados con nososotros.</p>


	<div class="row mt-4 justify-content-md-center">

		<table class="table table-hover col-12">
			<thead>
				<tr class="d-flex bg-primary text-white text-center">
					<th class="col-1">N°</th>
					<th class="col-3">Nombre</th>
					<th class="col-1">DUI</th>
					<th class="col-2">Resultado</th>
					
					<th class="col">Sintomas</th>
					<th class="col">Opciones</th>
				</tr>
			</thead>
			<tbody>
				{% for minsal in pacientes %}
				<tr class="d-flex text-center">
					<td class="col-1 font-weight-bold">{{ forloop.counter }}</td>
					<td class="col-3 font-weight-bold">{{minsal.paciente.nombre_paciente}} {{minsal.paciente.apellido_paciente}}</td>
					<td class="col-1">{{minsal.paciente.dui_paciente}}</td>
					
					{% if minsal.estado_paciente == True %}
							<td class="col-2">Positivo</td>
					{% else %}
							<td class="col-2">Negativo</td>
					{% endif %}
					<td class="col">{{ minsal.descripcion_paciente}}</td>
					<td class="col">

						<button class="btn btn-success" title="Editar Información del Laboratorista"
							data-toggle="modal" data-target="#editar-paciente-modal"
							data-id="{{minsal.paciente.idPaciente}}"
							data-nombre="{{minsal.paciente.nombre_paciente}}"
							data-apellido="{{minsal.paciente.apellido_paciente}}"
							data-dui="{{minsal.paciente.dui_paciente}}"
							data-desc="{{minsal.descripcion_paciente}}"
							data-fecha="{{minsal.paciente.fecha_paciente}}"
							data-sexo="{{minsal.paciente.sexo_paciente}}"
							data-estado="{{minsal.estado_paciente}}"
							
							

						>
						Editar&nbsp;&nbsp;<i class="fas fa-pen"></i>
						</button>
					</td>
				</tr>
				{% empty %}
				<tr>
					<td colspan="6">
						<h4>Aún no registras Pacientes.</h4>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
</div>

<!-- Modal mensaje de error -->
{% if messages %}
<div class="modal fade" id="mostrarmodal" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h3>Error al guardar el t&eacute;</h3>
			</div>
			{% for message in messages %}
			<div class="modal-body">
				<h4 {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</h4>
			</div>
			{% endfor %}
			<div class="modal-footer">
				<a href="#" data-dismiss="modal" class="btn btn-danger">Cerrar</a>
			</div>
		</div>
	</div>
</div>
{% endif %}

<!-- Modal Agregar laboratoristas -->
<div class="modal fade" id="agregar-minsal-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">

	<div class="modal-content">
	<form action="{% url 'registrar_paciente' %}" method="POST">

		<div class="modal-header">
			<h5 class="modal-title" id="exampleModalLabel">Agregar nuevo paciente</h5>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>

		<div class="modal-body">
			<div class="form-group row">
				<label for="nombre" class="col-sm-2 col-form-label">Nombre</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="nombre" name="nombre" placeholder="" required="">
				</div>
			</div>
			<div class="form-group row">
				<label for="apellido" class="col-sm-2 col-form-label">Apellido</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="apellido" name="apellido" placeholder="" required="">
				</div>
			</div>
			
			<div class="form-group row">
				<label for="dui" class="col-sm-2 col-form-label">DUI</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="dui" name="dui" placeholder="" required="">
				</div>
			</div>

			<div class="form-group row">
      			<label for="resultado" class="col-sm-2 col-form-label">Resultado: </label>
      			<div class="col-sm-10">
      				<select name="estado" id="estado" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
        			<option selected required="">Seleccione..</option>
        			<option value="1">Positivo</option>
        			<option value="0">Negativo</option>
      				</select>
      			</div>
    		</div>

    		<div class="form-group row">
      			<label for="fecha_propuesta" class="col-sm-2 col-form-label" >Sexo: </label>
      			<div class="col-sm-10">
      				<select name="sexo" id="sexo" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
        			<option selected required="">Seleccione..</option>
        			<option value="0">Masculino</option>
        			<option value="1">Femenino</option>
      				</select>
      			</div>
    		</div>
    		<div class="form-group row">
				<label for="fecha_propuesta" class="col-sm-2 col-form-label">Fecha de Nacimiento:</label>
				<div class="col-sm-10">
					<input type="date" class="form-control" id="fecha" name="fecha" placeholder="" required="">
				</div>
			</div>


			<div class="form-group row justify-content-md-center">
				
			</div>
		</div>
		
		<div class="modal-footer">
			{% csrf_token %}
			<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
			<button type="submit" class="btn btn-primary col-sm-4 col-form-label" id="Registrar">Registrar</button>
		</div>

	</form>
	</div>

</div>
</div>

<!-- Modal Editar Paciente -->
<div class="modal fade" id="editar-paciente-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">

	<div class="modal-content">
		
	<form action="{% url 'editar_paciente' %}" method="POST">

		<div class="modal-header">
			<h5 class="modal-title" id="exampleModalLabel">Editar paciente </h5>
			<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
			</button>
		</div>
	
		<div class="modal-body">
				<div class="form-group row d-none">
				<label for="id-edit" class="col-sm-2 col-form-label">ID de Cliente</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="id-edit" name="id_edit" placeholder="">
				</div>
			</div>
			<div class="form-group row">
				<label for="nombre" class="col-sm-2 col-form-label">Nombre</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="nombre-edit" name="nombre_edit" placeholder="" required="">
				</div>
			</div>
			<div class="form-group row">
				<label for="apellido" class="col-sm-2 col-form-label">Apellido</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="apellido-edit" name="apellido_edit" placeholder="" required="">
				</div>
			</div>
			
			<div class="form-group row">
				<label for="dui" class="col-sm-2 col-form-label">DUI</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="dui-edit" name="dui_edit" placeholder="" required="">
				</div>
			</div>

			<div class="form-group row">
      			<label for="resultado" class="col-sm-2 col-form-label">Resultado: </label>
      			<div class="col-sm-10">
      				<select id="estado-edit" name="estado_edit" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
        			<option selected required="">Seleccione..</option>
        			<option value="1">Positivo</option>
        			<option value="0">Negativo</option>
      				</select>
      			</div>
    		</div>

    		<div class="form-group row">
      			<label for="fecha_propuesta" class="col-sm-2 col-form-label" >Sexo: </label>
      			<div class="col-sm-10">
      				<select id="sexo-edit" name="sexo_edit" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
        			<option selected required="">Seleccione..</option>
        			<option value="0">Masculino</option>
        			<option value="1">Femenino</option>
      				</select>
      			</div>
    		</div>
    		<div class="form-group row">
				<label for="fecha_propuesta" class="col-sm-2 col-form-label">Fecha de Nacimiento:</label>
				<div class="col-sm-10">
					<input type="date" class="form-control" id="fecha-edit" name="fecha_edit" placeholder="" required="">
				</div>
			</div>
			<div class="form-group row">
      			<label for="correo" class="col-sm-2 col-form-label">Departamento:</label>
      			<div class="col-sm-10">
                    {{ form.departamento.label_tag }} 
                    {{ form.departamento }}
      			</div>
    		</div>
    		<div class="form-group row">
      			<label for="correo" class="col-sm-2 col-form-label">Municipio:</label>
      			<div class="col-sm-10">
                    {{ form.municipio.label_tag }} 
                    {{ form.municipio }}
      			</div>
    		</div>
    		<div class="form-group row">
					<label for="sintomas" class="col-sm-2 col-form-label">Sintomas</label>
					<div class="col-sm-10">
						<input type="text" class="form-control" id="sintomas" name="sintomas" placeholder="">
					</div>
			</div>
			<div class="form-group row justify-content-md-center">
				
			</div>
		</div>
		
		<div class="modal-footer">
			{% csrf_token %}
			<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
			<button type="submit" class="btn btn-primary col-sm-4 col-form-label" id="Registrar">Actualizar</button>
		</div>

		
	</form>
	</div>

</div>
</div>


<script>
	$(document).ready(function () {
		$("#mostrarmodal").modal("show");
	});
</script>